n_relations: 4

enable_log: true
kitti_pointcloud_root: '/home/nfs/inf6/data/datasets/SemanticKitti/' #'/path/to/semantic_kitti'
kitti_voxel_root: '../../../'
kitti_preprocess_root: '../../../kitti_preprocess/' #'/path/to/kitti/preprocess/folder'
kitti_logdir: '../../../kitti_logdir/' #'/path/to/semantic_kitti/logdir'

output_path: '../../slcfnet_output/'

fp_loss: true 
frustum_size: 8 
batch_size: 1  # each gpu could contain 1 continuous sample
inference_batch_size: 1
n_gpus: 1
num_workers_per_gpu: 3 
exp_prefix: 'exp' 
run: 1 
lr: 1e-4 
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true
inter_frame_loss: false

project_1_2: true
project_1_4: true
project_1_8: true




